version: '3.7'

services:
  test:
    container_name: cost-server-test
    build:
      context: .
      dockerfile: ./Dockerfile
      target: test
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    ports:
      - "${PORT}:${PORT}"
    command: npm run test

  dev:
    container_name: cost-server-dev
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    ports:
      - "${PORT}:${PORT}"
    command: npm run start:dev
    restart: always

  prod:
    container_name: cost-server-prod
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    ports:
      - "${PORT}:${PORT}"
    command: npm run start:prod
    restart: always

  nginx:
    image: nginx:1.15-alpine
    networks:
      - ssl-network
    depends_on:
      - certbot
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot:arm64v8-nightly
    networks:
      - ssl-network
    depends_on:
      - prod
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  postgres:
    container_name: cost-postgres
    image: postgres:latest
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:

networks:
  ssl-network: