version: '3.7'

services:
  test:
    container_name: cost-server-test
    build:
      context: .
      dockerfile: ./Dockerfile
      target: test
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    ports:
      - "${PORT}:${PORT}"
    command: npm run test
    networks:
      - cost-network

  dev:
    container_name: cost-server-dev
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    command: npm run start:dev
    restart: always
    networks:
      - cost-network

  debug:
    container_name: cost-server-debug
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    ports:
      - "${PORT}:${PORT}"
      - "9229:9229"
    env_file:
      - .env
    command: npm run start:debug
    restart: always
    networks:
      - cost-network

  prod:
    container_name: cost-server-prod
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    command: sh -c "npm run build && npm run start:prod"
    restart: always
    networks:
      - cost-network

  nginx:
    image: nginx:mainline-alpine
    container_name: cost-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - cost-network

  postgres:
    container_name: cost-postgres
    image: postgres:latest
    depends_on:
      - nginx
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - cost-network

volumes:
  pgdata:

networks:
  cost-network:
    driver: bridge